### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by iddq** [achuchev/arduino-keeloq-retransmit#1]
why do you want to replay a keeloq transmission if it won't be valid for second time?

**Comment by achuchev** [comment]
Yes you are right, the there is no value to send the code twice. But my use case is to retransmit the code to long distance. So I take the code from the rc (which is not in the range of the receiver) and immediately retransmit it.

**Comment by iddq** [comment]
good idea. can you recommend a hcs301 based transmitter from the market that is reprogrammable and good for playing?
